
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/mahir/VSCode/CutieHack/TkinterDesigner/build/assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1512x982")
window.configure(bg = "#FFFFFF")

def getUserInput():
    """
    User will enter their information

    Returns:
        _list_: Returns list containing information about the user which will be
                later used
    """
    
    height = float(entry_1.get())
    weight = float(entry_2.get())
    sex = entry_3.get()
    age = int(entry_4.get())
    
    activity_level = 0
    if button_1.clicked():
        print("WOWO")
    
    return [height, weight, sex, age, activity_level]



canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 982,
    width = 1512,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    19.0,
    29.0,
    1494.0,
    178.0,
    fill="#2300FD",
    outline="")

canvas.create_rectangle(
    19.0,
    213.0,
    235.0,
    284.0,
    fill="#F4B6BA",
    outline="")

canvas.create_text(
    480.0,
    41.0,
    anchor="nw",
    text="R’Nutrition",
    fill="#FFBE73",
    font=("Lalezar Regular", 96 * -1)
)

canvas.create_text(
    33.0,
    223.0,
    anchor="nw",
    text="Height (cm):",
    fill="#F13535",
    font=("Lalezar Regular", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    235.5,
    344.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=34.0,
    y=304.0,
    width=403.0,
    height=78.0
)

canvas.create_rectangle(
    19.0,
    404.0,
    280.0,
    476.0,
    fill="#FFBE73",
    outline="")

canvas.create_text(
    33.0,
    415.0,
    anchor="nw",
    text="Weight  (kg):",
    fill="#D37200",
    font=("Lalezar Regular", 40 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    235.5,
    536.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=34.0,
    y=496.0,
    width=403.0,
    height=78.0
)

canvas.create_rectangle(
    19.0,
    594.0,
    280.0,
    667.0,
    fill="#8CCDF1",
    outline="")

canvas.create_text(
    33.0,
    606.0,
    anchor="nw",
    text="Sex  (M/F):",
    fill="#005FEF",
    font=("Lalezar Regular", 40 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    235.5,
    727.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=34.0,
    y=687.0,
    width=403.0,
    height=78.0
)

canvas.create_rectangle(
    19.0,
    786.0,
    280.0,
    858.0,
    fill="#9DE17D",
    outline="")

canvas.create_text(
    33.0,
    797.0,
    anchor="nw",
    text="Age:",
    fill="#328025",
    font=("Lalezar Regular", 40 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    235.5,
    918.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=34.0,
    y=878.0,
    width=403.0,
    height=78.0
)

canvas.create_rectangle(
    19.0,
    213.0,
    280.0,
    284.0,
    fill="#F4B6BA",
    outline="")

canvas.create_text(
    33.0,
    223.0,
    anchor="nw",
    text="Height  (cm):",
    fill="#F13535",
    font=("Lalezar Regular", 40 * -1)
)

entry_image_5 = PhotoImage(
    file=relative_to_assets("entry_5.png"))
entry_bg_5 = canvas.create_image(
    235.5,
    344.0,
    image=entry_image_5
)
entry_5 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_5.place(
    x=34.0,
    y=304.0,
    width=403.0,
    height=78.0
)

canvas.create_rectangle(
    540.0,
    213.0,
    756.0,
    284.0,
    fill="#F4B6BA",
    outline="")

canvas.create_text(
    554.0,
    223.0,
    anchor="nw",
    text="Height (cm):",
    fill="#F13535",
    font=("Lalezar Regular", 40 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=540.0,
    y=304.0,
    width=433.0,
    height=80.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_2.place(
    x=540.0,
    y=522.0,
    width=433.0,
    height=80.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_3.place(
    x=540.0,
    y=413.0,
    width=433.0,
    height=80.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=540.0,
    y=631.0,
    width=433.0,
    height=80.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=540.0,
    y=740.0,
    width=433.0,
    height=80.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
)
button_6.place(
    x=1051.0,
    y=213.0,
    width=399.0,
    height=131.0
)

canvas.create_rectangle(
    540.0,
    213.0,
    973.0,
    284.0,
    fill="#D994F1",
    outline="")

canvas.create_text(
    554.0,
    223.0,
    anchor="nw",
    text="Activity Level",
    fill="#7F0F91",
    font=("Lalezar Regular", 40 * -1)
)
window.resizable(False, False)
window.mainloop()
